server:
  port: 8080

mybatis:
  mapper-locations: classpath*:/mybatis/sqls/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    cluster:
      url: jdbc:postgresql://localhost:5432/kakeibo
      username: root
      password: root
      driverClassName: org.postgresql.Driver
    reader:
      url: jdbc:postgresql://localhost:5432/kakeibo
      username: root
      password: root
      driverClassName: org.postgresql.Driver

logging.level.org.springframework.jdbc: debug