version: '3'
services:
  postgresql:
    image: postgres:12
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kakeibo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    hostname: postgres
    restart: always
    user: root